version: 0.0
os: linux
files: 
  - source: /
    destination: /home/ec2-user/python/
permissions:
  - object: /home/ec2-user/
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
      - location: scripts/clean_instance.sh
        timeout: 10
        runas: ec2-user
