version: 0.0
os: linux
files: 
  - source: /
    destination: /home/ec2-user/python/
permissions:
  - object: /home/ec2-user/
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
      - location: scripts/clean_instance.sh
        timeout: 10
        runas: ec2-user
  AfterInstall:
      - location: scripts/instance_os_dependencies.sh
        timeout: 10
        runas: ec2-user
  ApplicationStop:
      - location: scripts/stop_app.sh
        timeout: 10
        runas: ec2-user
  ApplicationStart:
      - location: scripts/start_app.sh
        timeout: 10
        runas: ec2-user
  
  
