version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g @angular/cli

  pre_build:
    commands:
      - npm install

  build:
    commands:
      - ng build

artifacts:
  files:
    - '**/*'
  base-directory: dist/
