version: 0.2

env:
    variables:
        BUILD_FOLDER: "dist"
phases:
  install:
    commands:
      # Uninstall existing Node.js (if any)
      - sudo apt-get purge nodejs npm

      # Install Node Version Manager (nvm)
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      - export NVM_DIR="$HOME/.nvm"
      - [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

      # Install Node.js version 12.x using nvm
      - nvm install 12

      # Use Node.js version 12.x
      - nvm use 12

      # Verify Node.js version
      - node --version
      - npm --version
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - echo Build started 
        - ng build
artifacts:
    files:
        - '**/*'
    base-directory: 'dist/Angular8JwtAuth*'
    discard-paths: yes
