version: 0.2


env:
    variables:
        BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli@12.2.18
        - echo GIT_BRANCH - $GIT_BRANCH
       
  build:
    commands:
        - echo Build started 
        - ng build
artifacts:
    files:
        - '**/*'
    base-directory: 'dist/Angular8JwtAuth*'
    discard-paths: yes

